NAME: "cifar-10"
MODEL:
  ARCHITECTURE: "resnet18mtl"
  CHANOUT: [10]
DATA:
  TRAIN:
    PATH: "/home/bmcv/Data/cifar-10-pngs/traintable.csv"
    FLIP: True
    ROTATE: False
    SHIFT: 4
  VAL:
    PATH: "/home/bmcv/Data/cifar-10-pngs/testtable.csv"
  TEST:
    PATH: "/home/bmcv/Data/cifar-10-pngs/testtable.csv"
  INFERENCE:
    PATH: "/home/bmcv/Data/cifar-10-pngs/testtable.csv"
HP:
  BATCHSIZE: 256
